# Generated by Django 4.2.2 on 2023-08-29 18:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recap', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='counter',
            name='words',
            field=models.TextField(default=''),
        ),
        migrations.AlterField(
            model_name='counter',
            name='counter',
            field=models.PositiveIntegerField(),
        ),
    ]
